### ISSUE TITLE
Service Discovery - DNS

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/staff-infrastructure-monitoring#114]
## User Story

As a network engineer
I want to view my device or instance by DNS hostname
So that I don't have to cross-reference IP addresses to hostnames

## Value

Consistency of instance naming across the platform

## Questions / Assumptions
Internal Zone within our DNS platform for e.g. network.service
we can join metrics if the instance changes from IP to hostname

## Definition of done

- [x] Add internal zone
- [x] IMAP to use MoJO DNS
- [x] Network devices to use MoJO DNS
- [ ] Prometheus to use [dns_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
@bagg3rs does this need a new issue in reference to the remaining work?

**Comment by bagg3rs** [comment]
Closing issue, we are now ready to use DNS Service Discovery to allow Prometheus to add targets based on DNS.
