### ISSUE TITLE
🔒 Cluster nodes obtaining IP addresses from both public and private subnets

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring#146]
The EKS cluster is configured to allow nodes to obtain IP addresses from both public and private subnets.  See code snippet below:
```hcl

module "monitoring_alerting_cluster" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "14.0.0"
  create_eks                      = var.is_eks_enabled
  cluster_name                    = "${var.prefix}-cluster"
  cluster_version                 = "1.19"
  manage_aws_auth                 = false
  cluster_endpoint_private_access = true
  cluster_enabled_log_types       = ["api", "authenticator", "controllerManager"]
  tags                            = var.tags

  subnets = concat(aws_subnet.private.*.id, aws_subnet.public.*.id)
  vpc_id  = aws_vpc.main.id

  worker_groups = [
    {
      name                 = "prometheus-worker-group"
      instance_type        = "t3.medium"
      asg_desired_capacity = 3
      root_volume_type     = "gp2"
    },
  ]
}
```

This presents a security concern as nodes should not be exposed to the internet unnecessarily.

**Comment by wanieldilson** [comment]
The steps taken to resolve on the Development environment are detailed below.  In order to remediate pre-prod and prod.  We will have to _manually_ delete the EKS cluster and then re-run our pipeline to recreate it.

1. From the [deployments repo](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments) run `make remove-workspace` against the environment you are remediating.  
1. Set `is_eks_enabled=false` on [main.tf](https://github.com/ministryofjustice/staff-infrastructure-monitoring/blob/a53507aa5a23ae8a5f818fe078bd228becae9b00/main.tf#L76). Once committed this will destroy the EKS cluster.
1. Replace `subnets = concat(aws_subnet.private.*.id, aws_subnet.public.*.id)` with `subnets = aws_subnet.private.*.id` in [modules/monitoring_platform/eks.tf](https://github.com/ministryofjustice/staff-infrastructure-monitoring/blob/a53507aa5a23ae8a5f818fe078bd228becae9b00/modules/monitoring_platform/eks.tf#L12). In the same commit, set `is_eks_enabled=true` on [main.tf](https://github.com/ministryofjustice/staff-infrastructure-monitoring/blob/a53507aa5a23ae8a5f818fe078bd228becae9b00/main.tf#L76).
1. From the [deployments repo](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments) run `make deploy` against the environment you are remediating. 
1. In the AWS Codepipeline UI, hit `Release Change` on the `staff-infrastructure-monitoring-config` pipeline.  This will reinstate the Prometheus config.

**Comment by mTouhid** [comment]
Once, k8s namespace has been removed using `make remove-workspace` command, if it is preferred to manually delete the EKS cluster, it is important to make sure:
1. EKS auto scaling group for the pre-existing EKS cluster is deleted and
2. All pre existing running EC2 worker node instances are terminated
