### ISSUE TITLE
Move slack_webhook_urls to parameter store from code

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/staff-infrastructure-monitoring#152]
User Story:As a Cloud Ops engineerI want to ensure secrets are stored securely in the parameter storeSo that they are not visible in our repositories

Value / Purpose  ensure secrets are securely stored and not openly available in code to improve security. 

Useful ContactsAaron Robinson and CloudOps team

Additional Informationhttps://github.com/ministryofjustice/staff-infrastructure-monitoring/security/secret-scanning/1

Definition of Done (DoD)slack_webhook_urls are referenced from the parameter store rather than being stored in code.

**Comment by bagg3rs** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring/152?planning-poker) with ZenHub @ASTRobinson @Gary-H9 @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by mTouhid** [comment]
The security alert related to this issue was generated from a very old commit on that repo and is no longer available in code on that repo. We closes the alert as 'False positive'.

Closing this issue as cancelled.
