### ISSUE TITLE
Custom Metric Historic Data < 24 Hours

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/staff-infrastructure-monitoring#174]
**Describe the bug**
There appears to be no data held longer than 24 hours for custom metrics in grafana.
**To Reproduce**
1. Go to service dashboard identify a custom metric graph.
2. Click on 'Time period > 24 Hours'
4. See No Data is visble

**Expected behavior**
No data is seen in custom metric graphs when the time period is > 24 hours.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/622a1024f6731fe223cfa94b/aeaced4c-665c-41aa-bf68-15a8f54ec13f)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10 Dev Build
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wanieldilson** [comment]
closed as part of #186
