### ISSUE TITLE
📖 Investigate Bastion ec2

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring#177]
## User Story

As a member of the CloudOps team  
I want to make sure unnecessary ec2 instances aren't live in AWS.
So that we don't waste money and increase our security posture 

## Value / Purpose

Ensure bastion ec2 isn't spun up when it shouldn't be

## Additional Information

![image](https://user-images.githubusercontent.com/68431297/160871722-115e85f4-5bbe-4482-9e76-e3a13e1751f3.png)

## Definition of Done (DoD)

Any test bastion ec2 instances are feature flagged and not created unnecessarily

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring/177?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
