### ISSUE TITLE
🧱Upgrade  VPC CNI version from v1.7.x or lower to v1.8.0 or above

### ISSUE THREAD

**Issue by mitchdawson1982** [ministryofjustice/staff-infrastructure-monitoring#180]
Affected Environments:
- mojo-development-ima-cluster
- mojo-pre-production-ima-cluster 
- mojo-production-ima-cluster

VPC CNI versions starting with v1.8.0 have the required fix to address this issue. Please upgrade to VPC CNI v1.8.0 or above if you are currently on the affected CNI versions on EKS v1.21 clusters. Our recommendation is to upgrade one minor version at a time. 

For example, if your current minor version is 1.8 and you want to update to 1.10, you should update to the latest patch version of 1.9 first, then update to the latest patch version of 1.10. Please refer to EKS documentation for instructions on upgrading the VPC CNI plugin [2].

NOTE:

We are currently configured to use the self managed add-on.

Procedure for migrating from the self managed add on to the eks add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#adding-vpc-cni-eks-add-on

Procedure  to update the self managed add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on

Procedure to update the eks add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-eks-add-on

If you have any questions or concerns, please contact AWS Support [3].

[1] https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume
[2] https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-eks-add-on
[3] https://aws.amazon.com/support

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring/180?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by mitchdawson1982** [comment]
We are currently configured to use the self managed add-on.

Procedure for migrating from the self managed add on to the eks add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#adding-vpc-cni-eks-add-on

Procedure  to update the self managed add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on

Procedure to update the eks add-on - https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-eks-add-on

**Comment by mTouhid** [comment]
VPC CNI has been upgraded.
From:
```
kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2 
amazon-k8s-cni-init:v1.7.5-eksbuild.1
amazon-k8s-cni:v1.7.5-eksbuild.1
```
To:
```
kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2 
amazon-k8s-cni-init:v1.11.0
amazon-k8s-cni:v1.11.0
```
