### ISSUE TITLE
📚 IMA S3 Bucket review 

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring#187]
## User Story

As a member of the CloudOps team 
I want to understand and document s3 use throughout IMA, and ensure all resources are necessary
So that I am  better prepared for any s3 related issues in future

## Value / Purpose

A better understanding of S3's role within the IMA platform.

## Additional Information

Please see #181 

## Definition of Done (DoD)

S3 section added to the documentation, any s3 buckets not being used by another resource should be deleted.

- [ ] README has been updated  
- [ ] `pttp-prometheus-thanos-storage` buckets are removed from each environment

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring/187?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by wanieldilson** [comment]
Closing for now, v low priority
