### ISSUE TITLE
Missing Metrics 'DHCP ECS Task count' (Pre-Prod / Development)

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/staff-infrastructure-monitoring#197]
**User Story**
As a Cloud Ops Engineer  
I want to see metrics from all environments  
So that I can successfully and easily manage DHCP.

**Value / Purpose**
All data is available on Grafana in one place making it easy to monitor our enviroments.

**Definition of Done (DoD)**
metric 'DHCP ECS Task count' is available for dev / pre-prod in Grafana.

Prod:
![image.png](https://images.zenhubusercontent.com/622a0d0186e6697a53098149/36928def-fae5-4ca5-aa17-9ffe5370fd22)

Pre-Prod / Dev:
![image.png](https://images.zenhubusercontent.com/622a0d0186e6697a53098149/f8861ae9-239c-46df-bb20-8ea5ff7e2a81)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring/197?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by ASTRobinson** [comment]
This issue has already been escalated with YACE: https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/497
I will monitor the issue and look for a workaround.
