### ISSUE TITLE
✨ Add `development` and `pre-production` namespaces in `production` EKS cluster

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/staff-infrastructure-monitoring#219]
### User Story

As a… developer in CloudOps team
I want to… test my code in development environment in Production EKS cluster
So that… I can my code in isolation without having to create a whole new EKS cluster

### Value / Purpose

This is reduce the cost of running additional EKS clusters for non-production environments.

### Useful Contacts

Touhidul Islam, Rich Baguley

### Definition of Done

- [ ] Production EKS cluster has all environments in separate namespaces
- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
After some discussion we have realised that in adding `development` and `pre-production` namespaces in `production` EKS cluster, we need to cleverly manipulate DNS. In addition @bagg3rs quantified the saving that we would make on this piece of work to circa £1000 / month per env.

Current approach, get the namespaces up and running in prod, then manually decommission the dev and preprod clusters.

**Comment by mTouhid** [comment]
Steps takes to fix the broken pipeline:
 - Edit CodeBuild projects in dev and pre-prod to change the service role to `production`
