### ISSUE TITLE
Please define external collaborators in code

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/staff-infrastructure-monitoring#22]
Hi there

We now have a process to manage github collaborators in code:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators

Please follow the procedure described there to grant @andycohen access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by bagg3rs** [comment]
andycohen has now been granted org access.
